// <auto-generated />
using System;
using InventoryBack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InventoryBack.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211021032733_Adding_relatioship_to_items_warehouse")]
    partial class Adding_relatioship_to_items_warehouse
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("InventoryBack.Models.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("InventoryBack.Models.Item_Warehouse", b =>
                {
                    b.Property<long>("Item_Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Warehouse_Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<bool>("enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Item_Id", "Warehouse_Id");

                    b.HasIndex("Warehouse_Id");

                    b.ToTable("item_Warehouses");
                });

            modelBuilder.Entity("InventoryBack.Models.Warehouse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("InventoryBack.Models.Item_Warehouse", b =>
                {
                    b.HasOne("InventoryBack.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("Item_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryBack.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("Warehouse_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Warehouse");
                });
#pragma warning restore 612, 618
        }
    }
}
